primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"
  AI_PROVIDER = "groq"
  ATLAS_ALLOW_ALL = "true"
  ATLAS_KB_PATH = "kb"
  ATLAS_KB_MAX_CHARS = "80000"
  AI_TEMPERATURE = "0.2"
  AI_MAX_TOKENS = "512"
  RATE_LIMIT_PER_MIN = "12"
  FAQ_CACHE_MAX = "200"
  ATLAS_SITE_URL = "https://atlassignals.site"

[processes]
  worker = "python main.py"

[checks]
  [checks.healthz]
    type = "http"
    port = 8000
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/healthz"

[deploy]
  strategy = "rolling" 